[config]
schemaVersion = "0.0.1"

[package]
namespace = "CardiaDarkhill"
name = "LegacyoftheAbyss"
versionNumber = "0.0.1"
description = "Legacy of the Abyss is a full co-op experience for Silksong. With a unique second playable character: The Shade!"
websiteUrl = "https://github.com/CardiaDarkhill/LegacyoftheAbyss"
containsNsfwContent = false
[package.dependencies]
silksong_modding-BepInExPack_Silksong = "1.0.3"


[build]
icon = "./BuildTemplates/Thunderstore/icon.png"
readme = "./BuildTemplates/Thunderstore/README.md"
outdir = "./build"

[[build.copy]]
source = "obj/Release/Thunderstore/LegacyoftheAbyss-__VERSION_PLACEHOLDER__/"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "hollow-knight-silksong", ]
[publish.categories]
hollow-knight-silksong = [ ]
